##Numpy
Designed for fast numerical computing

In [1]:
#importing Numpy
import numpy as np

##Numpy Array Creation using Builtin Methods

In [13]:
#creating Numpy Array
arr=np.array([1,2,3,4,5,6])
print(arr)

[1 2 3 4 5 6]


In [28]:
#creating Zeros Numpy Array
arr2=np.zeros((2,3))
print(arr2)

[[0. 0. 0.]
 [0. 0. 0.]]


In [33]:
#identity Matrix
arr3=np.eye(3)
print(arr3)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [34]:
#creating Numpy Array with a speicifed value
arr4=np.full((2,3),99)
print(arr4)

[[99 99 99]
 [99 99 99]]


In [32]:
#creating Numpy Array with all elements value 1
arr5=np.ones((2,3))
arr_ones=np.ones((4))
print(arr5)
print("\n",arr_ones)

[[1. 1. 1.]
 [1. 1. 1.]]

 [1. 1. 1. 1.]


In [37]:
#creating Numpy Array with arange Method
arr6=np.arange(1,11,2)
print(arr6)

[1 3 5 7 9]


In [217]:
#Eveny Spaced array [starting,Ending,totla values needed]
arr7=np.linspace(1,10,4)
print(arr7)

[ 1.  4.  7. 10.]


#Numpy Array vs Pyhton List Operations

In [162]:
lst=[1,2,3,4,5,6]
print(lst,type(lst))
print()
arr=np.array([1,2,3,4,5,])
print(arr,type(arr))

[1, 2, 3, 4, 5, 6] <class 'list'>

[1 2 3 4 5] <class 'numpy.ndarray'>


In [194]:
#list operation
n=[]
m=[]
for i in range(len(lst)):
 n.append(i*2)
 m.append(i+2)
print(n)
print(m)

[0, 2, 4, 6, 8, 10]
[2, 3, 4, 5, 6, 7]


In [164]:
#Numpy array operations
print(arr*2)
print(arr+2)


[ 2  4  6  8 10]
[3 4 5 6 7]


##Properties

In [165]:
arr=np.array([1,2,3,4,5])
print(arr.shape)
print(arr.ndim)
print(arr.size)
print(arr.dtype)


(5,)
1
5
int64


In [166]:
#2D array
arr2=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr2)
print(type(arr))
print(arr2.shape)
print(arr2.ndim)
print(arr2.size)
print(arr2.dtype)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
<class 'numpy.ndarray'>
(2, 5)
2
10
int64


In [167]:
float_array=np.array([1,2,3,4,5],dtype=np.float64)
print(float_array,float_array.dtype)

[1. 2. 3. 4. 5.] float64


##Opertions & Indexing

In [168]:
arr=np.array([1,2,3,4,5,6])
arr.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [169]:
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr)
arr.flatten()

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [170]:
idx=np.array([1,2,3,4,5,6,7])
print(idx[3])
print(idx[0])
print(idx[-1])


4
1
7


In [171]:
idx2=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(idx2)

print(idx2[0][0])
print(idx2[0][2])
print(idx2[1][0])
print(idx2[1][3])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
1
3
6
9


In [172]:
#3D array(1 Depth)
arr3d=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(arr3d)
print(arr3d.shape)
print(arr3d.ndim)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
(1, 3, 3)
3


In [173]:
#array[depth][row][col]
print(arr3d[0][2][1])
print(arr3d[0][1][1])

8
5


In [174]:
arr3d.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [175]:
#3D array(2 Depth)
arr3d=np.array([[[1,2,3],[4,5,6],[7,8,9]],[[11,12,13],[14,15,16],[17,18,19]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[11, 12, 13],
        [14, 15, 16],
        [17, 18, 19]]])

In [176]:
print(arr3d[0][0][0])
print(arr3d[0][1][1])
print(arr3d[0][2][2])


1
5
9


In [177]:
#2nd Depth
print(arr3d[1][0][0])
print(arr3d[1][1][1])
print(arr3d[1][2][2])

11
15
19


In [206]:
print(arr3d[0][0][0])
print(arr3d[0][2][1])
print(arr3d[1][0][0])
#2nd method
print("2nd Method  of Indexing")
print(arr3d[1,2,1])
print(arr3d[0,0,0])
print(arr3d[0,2,1])

1
8
11
2nd Method  of Indexing
18
1
8


In [179]:
arr3d.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [180]:
#Fancy Indexing
arr=np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
idx=[2,4,6,8]
arr[idx]

array([3, 5, 7, 9])

In [181]:
arrr=np.array([[1, 2, 3, 4,] ,[5, 6, 7, 8]])
idxx=[0]
arrr[idxx]

array([[1, 2, 3, 4]])

In [182]:
#Boolean indexing
print(arr)
print(arr[arr>3])
print(arr[arr<5])
print(arr[arr%2==0])

[1 2 3 4 5 6 7 8 9]
[4 5 6 7 8 9]
[1 2 3 4]
[2 4 6 8]


##Slicing
array[start:End:Step]

**Note:** It create view of that array not copy of sliced array(if changing the sliced elements orignal array also change)

In [183]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [184]:
arr[2:8]

array([3, 4, 5, 6, 7, 8])

In [185]:
arr[0:9:2]

array([1, 3, 5, 7, 9])

In [186]:
arr[0:9:3]

array([1, 4, 7])

In [187]:
arr[::2]

array([1, 3, 5, 7, 9])

In [188]:
#Slicing on 2D arrays
arrr

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [189]:
arrr[0,2:]

array([3, 4])

In [190]:
arrr[:,1:3]

array([[2, 3],
       [6, 7]])

In [191]:
arrr[1,:]

array([5, 6, 7, 8])

In [197]:
view=arr[0:4]
print(view)
view[0]=11
print(view)
print(arr)

[11  2  3  4]
[11  2  3  4]
[11  2  3  4  5  6  7  8  9]


In [199]:
#3D Array Slicing
arr3d=np.array([[[1,2,3],[4,5,6],[7,8,9]],[[11,12,13],[14,15,16],[17,18,19]]])
print(arr3d,arr3d.shape)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[11 12 13]
  [14 15 16]
  [17 18 19]]] (2, 3, 3)


In [216]:
#array[depth,row,col]
print(arr3d[0,0,:])
print()
print(arr3d[1,0,:])
print()
print(arr3d[:,0,:])
print()
print(arr3d[:,:,0])
print()
print(arr3d[:,:,1])
print()
print(arr3d[:,:,2])

[1 2 3]

[11 12 13]

[[ 1  2  3]
 [11 12 13]]

[[ 1  4  7]
 [11 14 17]]

[[ 2  5  8]
 [12 15 18]]

[[ 3  6  9]
 [13 16 19]]


##Vectorization

Operation will perform ones on all array elements

In [218]:
arr=np.array([1,2,3,4])
print(arr+2)
print(arr*3)
print(arr/2)
print(arr**2)

[3 4 5 6]
[ 3  6  9 12]


In [220]:
arr2=np.array([5,6,7,8])
print(arr+arr2)

[ 6  8 10 12]


#Broadcasting
Scaling an array with out using extra memory
**Imp:** Two dimensions are compatible when

they are equal-->(3,3),(3,3) or

one of them is 1-->(2,2),(1,2).

In [224]:
arr=np.array([1,2,3,4])
arr2=np.array([5,6,7])
print(arr.shape)
print(arr2.shape)
#it will through error as arr shape is (4,)and arr2 is (3,)
# print(arr+arr2)

(4,)
(3,)


In [228]:
arr=np.array([1,2,3,4,5]) #shape (5,1)
print(arr.shape)
arr2=np.array([[1,2,3,4,5],[6,7,8,9,10]]) #shape (2,5)
print(arr2.shape)
print(arr+arr2)

(5,)
(2, 5)
[[ 2  4  6  8 10]
 [ 7  9 11 13 15]]


##Mathematical Functions

In [235]:
print(arr)
print(np.sum(arr))
print(np.prod(arr))
print(np.min(arr))
print(np.max(arr))
print(np.std(arr))
print(np.var(arr))


print(np.mean(arr))
print(np.median(arr))

[1 2 3 4 5]
15
120
1
5
1.4142135623730951
2.0
3.0
3.0


In [239]:
#power functions
print(np.sqrt(arr))
print(np.square(arr))
print(np.pow(arr,3))

[1.         1.41421356 1.73205081 2.         2.23606798]
[ 1  4  9 16 25]
[  1   8  27  64 125]


In [241]:
#log()
print(np.log(arr))
print(np.log10(arr))

[0.         0.69314718 1.09861229 1.38629436 1.60943791]
[0.         0.30103    0.47712125 0.60205999 0.69897   ]


In [243]:
print(np.floor(3.14))
print(np.ceil(3.14))
print(np.round(3.14))
print(np.trunc(3.14))

3.0
4.0
3.0
3.0


In [245]:
arr=np.array([1,2,1,3,4,5,6,3,5])
print(np.unique(arr))
print(np.sort(arr))
print(np.sqrt(arr))

[1 2 3 4 5 6]
[1 1 2 3 3 4 5 5 6]
[1.         1.41421356 1.         1.73205081 2.         2.23606798
 2.44948974 1.73205081 2.23606798]
